name: Build BoringSSL with liboqs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE: caddy-forwardproxy-naive
      BORINGSSL_BRANCH: master
      BORINGSSL_DIR: /home/runner/work/forwardproxy/forwardproxy/boringssl
      LIBOQS_DIR: /home/runner/work/forwardproxy/forwardproxy/liboqs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev cmake ninja-build

    - name: Clone and build liboqs
      run: |
        git clone --branch main https://github.com/open-quantum-safe/liboqs.git $LIBOQS_DIR
        cd $LIBOQS_DIR
        mkdir build && cd build
        cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local ..
        ninja
        sudo ninja install

    - name: Clone and build BoringSSL
      run: |
        rm -rf boringssl
        git clone https://github.com/open-quantum-safe/boringssl.git
        cd boringssl
        git checkout $BORINGSSL_BRANCH
        mkdir build && cd build
        cmake -GNinja -DCMAKE_PREFIX_PATH=/usr/local ..
        ninja
